/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppShellRouteRouteImport } from './routes/_appShell/route'
import { Route as ServerShellRouteRouteImport } from './routes/_serverShell/route'
import { Route as StorageShellRouteRouteImport } from './routes/_storageShell/route'
import { Route as AppShellIndexRouteImport } from './routes/_appShell/index'
import { Route as AppShellSplatRouteImport } from './routes/_appShell/$'
import { Route as AppShellKeychainRouteImport } from './routes/_appShell/keychain'
import { Route as AppShellProjectsRouteImport } from './routes/_appShell/projects'
import { Route as AppShellSettingsRouteImport } from './routes/_appShell/settings'
import { Route as AppShellStorageRouteImport } from './routes/_appShell/storage'
import { Route as AppShellProjectIdRouteImport } from './routes/_appShell/project/$id'
import { Route as ServerShellServerIdRouteRouteImport } from './routes/_serverShell/server/$id/route'
import { Route as StorageShellStorageIdRouteRouteImport } from './routes/_storageShell/storage/$id/route'
import { Route as ServerShellServerIdIndexRouteImport } from './routes/_serverShell/server/$id/index'
import { Route as ServerShellServerIdFilesRouteImport } from './routes/_serverShell/server/$id/files'
import { Route as ServerShellServerIdMonitorRouteImport } from './routes/_serverShell/server/$id/monitor'
import { Route as ServerShellServerIdOsRouteImport } from './routes/_serverShell/server/$id/os'
import { Route as ServerShellServerIdOverviewRouteImport } from './routes/_serverShell/server/$id/overview'
import { Route as ServerShellServerIdSettingsRouteImport } from './routes/_serverShell/server/$id/settings'
import { Route as ServerShellServerIdTerminalRouteImport } from './routes/_serverShell/server/$id/terminal'
import { Route as StorageShellStorageIdIndexRouteImport } from './routes/_storageShell/storage/$id/index'
import { Route as StorageShellStorageIdOverviewRouteImport } from './routes/_storageShell/storage/$id/overview'
import { Route as StorageShellStorageIdSettingsRouteImport } from './routes/_storageShell/storage/$id/settings'
import { Route as StorageShellStorageIdBBucketRouteImport } from './routes/_storageShell/storage/$id/b/$bucket'

const AppShellRouteRoute = AppShellRouteRouteImport.update({
  id: '/_appShell',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerShellRouteRoute = ServerShellRouteRouteImport.update({
  id: '/_serverShell',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageShellRouteRoute = StorageShellRouteRouteImport.update({
  id: '/_storageShell',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShellIndexRoute = AppShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSplatRoute = AppShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellKeychainRoute = AppShellKeychainRouteImport.update({
  id: '/keychain',
  path: '/keychain',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellProjectsRoute = AppShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellSettingsRoute = AppShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellStorageRoute = AppShellStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const AppShellProjectIdRoute = AppShellProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppShellRouteRoute,
} as any)
const ServerShellServerIdRouteRoute =
  ServerShellServerIdRouteRouteImport.update({
    id: '/server/$id',
    path: '/server/$id',
    getParentRoute: () => ServerShellRouteRoute,
  } as any)
const StorageShellStorageIdRouteRoute =
  StorageShellStorageIdRouteRouteImport.update({
    id: '/storage/$id',
    path: '/storage/$id',
    getParentRoute: () => StorageShellRouteRoute,
  } as any)
const ServerShellServerIdIndexRoute =
  ServerShellServerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const ServerShellServerIdFilesRoute =
  ServerShellServerIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const ServerShellServerIdMonitorRoute =
  ServerShellServerIdMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const ServerShellServerIdOsRoute = ServerShellServerIdOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => ServerShellServerIdRouteRoute,
} as any)
const ServerShellServerIdOverviewRoute =
  ServerShellServerIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const ServerShellServerIdSettingsRoute =
  ServerShellServerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const ServerShellServerIdTerminalRoute =
  ServerShellServerIdTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => ServerShellServerIdRouteRoute,
  } as any)
const StorageShellStorageIdIndexRoute =
  StorageShellStorageIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StorageShellStorageIdRouteRoute,
  } as any)
const StorageShellStorageIdOverviewRoute =
  StorageShellStorageIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => StorageShellStorageIdRouteRoute,
  } as any)
const StorageShellStorageIdSettingsRoute =
  StorageShellStorageIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => StorageShellStorageIdRouteRoute,
  } as any)
const StorageShellStorageIdBBucketRoute =
  StorageShellStorageIdBBucketRouteImport.update({
    id: '/b/$bucket',
    path: '/b/$bucket',
    getParentRoute: () => StorageShellStorageIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppShellIndexRoute
  '/$': typeof AppShellSplatRoute
  '/keychain': typeof AppShellKeychainRoute
  '/projects': typeof AppShellProjectsRoute
  '/settings': typeof AppShellSettingsRoute
  '/storage': typeof AppShellStorageRoute
  '/server/$id': typeof ServerShellServerIdRouteRouteWithChildren
  '/storage/$id': typeof StorageShellStorageIdRouteRouteWithChildren
  '/project/$id': typeof AppShellProjectIdRoute
  '/server/$id/files': typeof ServerShellServerIdFilesRoute
  '/server/$id/monitor': typeof ServerShellServerIdMonitorRoute
  '/server/$id/os': typeof ServerShellServerIdOsRoute
  '/server/$id/overview': typeof ServerShellServerIdOverviewRoute
  '/server/$id/settings': typeof ServerShellServerIdSettingsRoute
  '/server/$id/terminal': typeof ServerShellServerIdTerminalRoute
  '/storage/$id/overview': typeof StorageShellStorageIdOverviewRoute
  '/storage/$id/settings': typeof StorageShellStorageIdSettingsRoute
  '/server/$id/': typeof ServerShellServerIdIndexRoute
  '/storage/$id/': typeof StorageShellStorageIdIndexRoute
  '/storage/$id/b/$bucket': typeof StorageShellStorageIdBBucketRoute
}
export interface FileRoutesByTo {
  '/': typeof AppShellIndexRoute
  '/$': typeof AppShellSplatRoute
  '/keychain': typeof AppShellKeychainRoute
  '/projects': typeof AppShellProjectsRoute
  '/settings': typeof AppShellSettingsRoute
  '/storage': typeof AppShellStorageRoute
  '/project/$id': typeof AppShellProjectIdRoute
  '/server/$id/files': typeof ServerShellServerIdFilesRoute
  '/server/$id/monitor': typeof ServerShellServerIdMonitorRoute
  '/server/$id/os': typeof ServerShellServerIdOsRoute
  '/server/$id/overview': typeof ServerShellServerIdOverviewRoute
  '/server/$id/settings': typeof ServerShellServerIdSettingsRoute
  '/server/$id/terminal': typeof ServerShellServerIdTerminalRoute
  '/storage/$id/overview': typeof StorageShellStorageIdOverviewRoute
  '/storage/$id/settings': typeof StorageShellStorageIdSettingsRoute
  '/server/$id': typeof ServerShellServerIdIndexRoute
  '/storage/$id': typeof StorageShellStorageIdIndexRoute
  '/storage/$id/b/$bucket': typeof StorageShellStorageIdBBucketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appShell': typeof AppShellRouteRouteWithChildren
  '/_serverShell': typeof ServerShellRouteRouteWithChildren
  '/_storageShell': typeof StorageShellRouteRouteWithChildren
  '/_appShell/$': typeof AppShellSplatRoute
  '/_appShell/keychain': typeof AppShellKeychainRoute
  '/_appShell/projects': typeof AppShellProjectsRoute
  '/_appShell/settings': typeof AppShellSettingsRoute
  '/_appShell/storage': typeof AppShellStorageRoute
  '/_appShell/': typeof AppShellIndexRoute
  '/_serverShell/server/$id': typeof ServerShellServerIdRouteRouteWithChildren
  '/_storageShell/storage/$id': typeof StorageShellStorageIdRouteRouteWithChildren
  '/_appShell/project/$id': typeof AppShellProjectIdRoute
  '/_serverShell/server/$id/files': typeof ServerShellServerIdFilesRoute
  '/_serverShell/server/$id/monitor': typeof ServerShellServerIdMonitorRoute
  '/_serverShell/server/$id/os': typeof ServerShellServerIdOsRoute
  '/_serverShell/server/$id/overview': typeof ServerShellServerIdOverviewRoute
  '/_serverShell/server/$id/settings': typeof ServerShellServerIdSettingsRoute
  '/_serverShell/server/$id/terminal': typeof ServerShellServerIdTerminalRoute
  '/_storageShell/storage/$id/overview': typeof StorageShellStorageIdOverviewRoute
  '/_storageShell/storage/$id/settings': typeof StorageShellStorageIdSettingsRoute
  '/_serverShell/server/$id/': typeof ServerShellServerIdIndexRoute
  '/_storageShell/storage/$id/': typeof StorageShellStorageIdIndexRoute
  '/_storageShell/storage/$id/b/$bucket': typeof StorageShellStorageIdBBucketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/keychain'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/server/$id'
    | '/storage/$id'
    | '/project/$id'
    | '/server/$id/files'
    | '/server/$id/monitor'
    | '/server/$id/os'
    | '/server/$id/overview'
    | '/server/$id/settings'
    | '/server/$id/terminal'
    | '/storage/$id/overview'
    | '/storage/$id/settings'
    | '/server/$id/'
    | '/storage/$id/'
    | '/storage/$id/b/$bucket'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/keychain'
    | '/projects'
    | '/settings'
    | '/storage'
    | '/project/$id'
    | '/server/$id/files'
    | '/server/$id/monitor'
    | '/server/$id/os'
    | '/server/$id/overview'
    | '/server/$id/settings'
    | '/server/$id/terminal'
    | '/storage/$id/overview'
    | '/storage/$id/settings'
    | '/server/$id'
    | '/storage/$id'
    | '/storage/$id/b/$bucket'
  id:
    | '__root__'
    | '/_appShell'
    | '/_serverShell'
    | '/_storageShell'
    | '/_appShell/$'
    | '/_appShell/keychain'
    | '/_appShell/projects'
    | '/_appShell/settings'
    | '/_appShell/storage'
    | '/_appShell/'
    | '/_serverShell/server/$id'
    | '/_storageShell/storage/$id'
    | '/_appShell/project/$id'
    | '/_serverShell/server/$id/files'
    | '/_serverShell/server/$id/monitor'
    | '/_serverShell/server/$id/os'
    | '/_serverShell/server/$id/overview'
    | '/_serverShell/server/$id/settings'
    | '/_serverShell/server/$id/terminal'
    | '/_storageShell/storage/$id/overview'
    | '/_storageShell/storage/$id/settings'
    | '/_serverShell/server/$id/'
    | '/_storageShell/storage/$id/'
    | '/_storageShell/storage/$id/b/$bucket'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppShellRouteRoute: typeof AppShellRouteRouteWithChildren
  ServerShellRouteRoute: typeof ServerShellRouteRouteWithChildren
  StorageShellRouteRoute: typeof StorageShellRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appShell': {
      id: '/_appShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_serverShell': {
      id: '/_serverShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ServerShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_storageShell': {
      id: '/_storageShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StorageShellRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appShell/': {
      id: '/_appShell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppShellIndexRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/$': {
      id: '/_appShell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppShellSplatRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/keychain': {
      id: '/_appShell/keychain'
      path: '/keychain'
      fullPath: '/keychain'
      preLoaderRoute: typeof AppShellKeychainRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/projects': {
      id: '/_appShell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppShellProjectsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/settings': {
      id: '/_appShell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppShellSettingsRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/storage': {
      id: '/_appShell/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppShellStorageRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_appShell/project/$id': {
      id: '/_appShell/project/$id'
      path: '/project/$id'
      fullPath: '/project/$id'
      preLoaderRoute: typeof AppShellProjectIdRouteImport
      parentRoute: typeof AppShellRouteRoute
    }
    '/_serverShell/server/$id': {
      id: '/_serverShell/server/$id'
      path: '/server/$id'
      fullPath: '/server/$id'
      preLoaderRoute: typeof ServerShellServerIdRouteRouteImport
      parentRoute: typeof ServerShellRouteRoute
    }
    '/_storageShell/storage/$id': {
      id: '/_storageShell/storage/$id'
      path: '/storage/$id'
      fullPath: '/storage/$id'
      preLoaderRoute: typeof StorageShellStorageIdRouteRouteImport
      parentRoute: typeof StorageShellRouteRoute
    }
    '/_serverShell/server/$id/': {
      id: '/_serverShell/server/$id/'
      path: '/'
      fullPath: '/server/$id/'
      preLoaderRoute: typeof ServerShellServerIdIndexRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/files': {
      id: '/_serverShell/server/$id/files'
      path: '/files'
      fullPath: '/server/$id/files'
      preLoaderRoute: typeof ServerShellServerIdFilesRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/monitor': {
      id: '/_serverShell/server/$id/monitor'
      path: '/monitor'
      fullPath: '/server/$id/monitor'
      preLoaderRoute: typeof ServerShellServerIdMonitorRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/os': {
      id: '/_serverShell/server/$id/os'
      path: '/os'
      fullPath: '/server/$id/os'
      preLoaderRoute: typeof ServerShellServerIdOsRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/overview': {
      id: '/_serverShell/server/$id/overview'
      path: '/overview'
      fullPath: '/server/$id/overview'
      preLoaderRoute: typeof ServerShellServerIdOverviewRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/settings': {
      id: '/_serverShell/server/$id/settings'
      path: '/settings'
      fullPath: '/server/$id/settings'
      preLoaderRoute: typeof ServerShellServerIdSettingsRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_serverShell/server/$id/terminal': {
      id: '/_serverShell/server/$id/terminal'
      path: '/terminal'
      fullPath: '/server/$id/terminal'
      preLoaderRoute: typeof ServerShellServerIdTerminalRouteImport
      parentRoute: typeof ServerShellServerIdRouteRoute
    }
    '/_storageShell/storage/$id/': {
      id: '/_storageShell/storage/$id/'
      path: '/'
      fullPath: '/storage/$id/'
      preLoaderRoute: typeof StorageShellStorageIdIndexRouteImport
      parentRoute: typeof StorageShellStorageIdRouteRoute
    }
    '/_storageShell/storage/$id/overview': {
      id: '/_storageShell/storage/$id/overview'
      path: '/overview'
      fullPath: '/storage/$id/overview'
      preLoaderRoute: typeof StorageShellStorageIdOverviewRouteImport
      parentRoute: typeof StorageShellStorageIdRouteRoute
    }
    '/_storageShell/storage/$id/settings': {
      id: '/_storageShell/storage/$id/settings'
      path: '/settings'
      fullPath: '/storage/$id/settings'
      preLoaderRoute: typeof StorageShellStorageIdSettingsRouteImport
      parentRoute: typeof StorageShellStorageIdRouteRoute
    }
    '/_storageShell/storage/$id/b/$bucket': {
      id: '/_storageShell/storage/$id/b/$bucket'
      path: '/b/$bucket'
      fullPath: '/storage/$id/b/$bucket'
      preLoaderRoute: typeof StorageShellStorageIdBBucketRouteImport
      parentRoute: typeof StorageShellStorageIdRouteRoute
    }
  }
}

interface AppShellRouteRouteChildren {
  AppShellSplatRoute: typeof AppShellSplatRoute
  AppShellKeychainRoute: typeof AppShellKeychainRoute
  AppShellProjectsRoute: typeof AppShellProjectsRoute
  AppShellSettingsRoute: typeof AppShellSettingsRoute
  AppShellStorageRoute: typeof AppShellStorageRoute
  AppShellIndexRoute: typeof AppShellIndexRoute
  AppShellProjectIdRoute: typeof AppShellProjectIdRoute
}

const AppShellRouteRouteChildren: AppShellRouteRouteChildren = {
  AppShellSplatRoute: AppShellSplatRoute,
  AppShellKeychainRoute: AppShellKeychainRoute,
  AppShellProjectsRoute: AppShellProjectsRoute,
  AppShellSettingsRoute: AppShellSettingsRoute,
  AppShellStorageRoute: AppShellStorageRoute,
  AppShellIndexRoute: AppShellIndexRoute,
  AppShellProjectIdRoute: AppShellProjectIdRoute,
}

const AppShellRouteRouteWithChildren = AppShellRouteRoute._addFileChildren(
  AppShellRouteRouteChildren,
)

interface ServerShellServerIdRouteRouteChildren {
  ServerShellServerIdFilesRoute: typeof ServerShellServerIdFilesRoute
  ServerShellServerIdMonitorRoute: typeof ServerShellServerIdMonitorRoute
  ServerShellServerIdOsRoute: typeof ServerShellServerIdOsRoute
  ServerShellServerIdOverviewRoute: typeof ServerShellServerIdOverviewRoute
  ServerShellServerIdSettingsRoute: typeof ServerShellServerIdSettingsRoute
  ServerShellServerIdTerminalRoute: typeof ServerShellServerIdTerminalRoute
  ServerShellServerIdIndexRoute: typeof ServerShellServerIdIndexRoute
}

const ServerShellServerIdRouteRouteChildren: ServerShellServerIdRouteRouteChildren =
  {
    ServerShellServerIdFilesRoute: ServerShellServerIdFilesRoute,
    ServerShellServerIdMonitorRoute: ServerShellServerIdMonitorRoute,
    ServerShellServerIdOsRoute: ServerShellServerIdOsRoute,
    ServerShellServerIdOverviewRoute: ServerShellServerIdOverviewRoute,
    ServerShellServerIdSettingsRoute: ServerShellServerIdSettingsRoute,
    ServerShellServerIdTerminalRoute: ServerShellServerIdTerminalRoute,
    ServerShellServerIdIndexRoute: ServerShellServerIdIndexRoute,
  }

const ServerShellServerIdRouteRouteWithChildren =
  ServerShellServerIdRouteRoute._addFileChildren(
    ServerShellServerIdRouteRouteChildren,
  )

interface ServerShellRouteRouteChildren {
  ServerShellServerIdRouteRoute: typeof ServerShellServerIdRouteRouteWithChildren
}

const ServerShellRouteRouteChildren: ServerShellRouteRouteChildren = {
  ServerShellServerIdRouteRoute: ServerShellServerIdRouteRouteWithChildren,
}

const ServerShellRouteRouteWithChildren =
  ServerShellRouteRoute._addFileChildren(ServerShellRouteRouteChildren)

interface StorageShellStorageIdRouteRouteChildren {
  StorageShellStorageIdOverviewRoute: typeof StorageShellStorageIdOverviewRoute
  StorageShellStorageIdSettingsRoute: typeof StorageShellStorageIdSettingsRoute
  StorageShellStorageIdIndexRoute: typeof StorageShellStorageIdIndexRoute
  StorageShellStorageIdBBucketRoute: typeof StorageShellStorageIdBBucketRoute
}

const StorageShellStorageIdRouteRouteChildren: StorageShellStorageIdRouteRouteChildren =
  {
    StorageShellStorageIdOverviewRoute: StorageShellStorageIdOverviewRoute,
    StorageShellStorageIdSettingsRoute: StorageShellStorageIdSettingsRoute,
    StorageShellStorageIdIndexRoute: StorageShellStorageIdIndexRoute,
    StorageShellStorageIdBBucketRoute: StorageShellStorageIdBBucketRoute,
  }

const StorageShellStorageIdRouteRouteWithChildren =
  StorageShellStorageIdRouteRoute._addFileChildren(
    StorageShellStorageIdRouteRouteChildren,
  )

interface StorageShellRouteRouteChildren {
  StorageShellStorageIdRouteRoute: typeof StorageShellStorageIdRouteRouteWithChildren
}

const StorageShellRouteRouteChildren: StorageShellRouteRouteChildren = {
  StorageShellStorageIdRouteRoute: StorageShellStorageIdRouteRouteWithChildren,
}

const StorageShellRouteRouteWithChildren =
  StorageShellRouteRoute._addFileChildren(StorageShellRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppShellRouteRoute: AppShellRouteRouteWithChildren,
  ServerShellRouteRoute: ServerShellRouteRouteWithChildren,
  StorageShellRouteRoute: StorageShellRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
